### ISSUE TITLE
API nonfunctional

### ISSUE THREAD

**Issue by boomshakazulu** [nikasepiskveradze/war-statistics-api#1]
API's non-functional 404 error.

the only requests that seem to work are the "type" requests, the rest 404

**Comment by nikasepiskveradze** [comment]
> API's non-functional 404 error.
> 
> the only requests that seem to work are the "type" requests, the rest 404

Could you show me some example where you get the error? for me it seems to work fine, note that some endpoints are POST requests maybe that's the problem

**Comment by boomshakazulu** [comment]
if they're post requests doesn't that make it impossible to get the data? a post would be creating data. 
where it stands if you do a get request to the main url "https://war-track.com/" you receive the entire website and if you do a post request to the other sections you dont receive info you're only updating info. which is probably not the best option to allow anyone to update your data and not be able to receive any of it.

seems like you would want a way to receive only the data through get commands with params rather than receiving your entire homepage and trying to parse out the data. it's so much that insomnia cant handle the request.
![main](https://github.com/nikasepiskveradze/war-track-api/assets/120769113/8741b10b-4104-4c28-aecc-f82d44d69e2a)
![equipments](https://github.com/nikasepiskveradze/war-track-api/assets/120769113/073d322c-720b-4734-a6c2-16ab5fff9669)

**Comment by nikasepiskveradze** [comment]
> if they're post requests doesn't that make it impossible to get the data? a post would be creating data. where it stands if you do a get request to the main url "https://war-track.com/" you receive the entire website and if you do a post request to the other sections you dont receive info you're only updating info. which is probably not the best option to allow anyone to update your data and not be able to receive any of it.
> 
> seems like you would want a way to receive only the data through get commands with params rather than receiving your entire homepage and trying to parse out the data. it's so much that insomnia cant handle the request. ![main](https://private-user-images.githubusercontent.com/120769113/286117531-8741b10b-4104-4c28-aecc-f82d44d69e2a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDU1NDMsIm5iZiI6MTcwMTE0NTI0MywicGF0aCI6Ii8xMjA3NjkxMTMvMjg2MTE3NTMxLTg3NDFiMTBiLTQxMDQtNGMyOC1hZWNjLWY4MmQ0NGQ2OWUyYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwNDIwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmM2Yzk1MmQ0ZmYyOTcxMjJjNzYyMGI3OGZlMDhmZWQ4OThjYzViNmFiNWZkODQ5M2M1OTY0ZmJkODY4ZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k3_mUsh1r3NU0g3ROcRIOgEcimXF958gsmAKbDFHgRY) ![equipments](https://private-user-images.githubusercontent.com/120769113/286117537-073d322c-720b-4734-a6c2-16ab5fff9669.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDU1NDMsIm5iZiI6MTcwMTE0NTI0MywicGF0aCI6Ii8xMjA3NjkxMTMvMjg2MTE3NTM3LTA3M2QzMjJjLTcyMGItNDczNC1hNmMyLTE2YWI1ZmZmOTY2OS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwNDIwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzI2NzYzNjYwMDBlOWFhNGEzYThkMjkxOGNiYTE5MTA1M2JiN2VhZjAyNWNjZDNlYjNkZjkxMDYwZDJhZTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5gNfn-UU3tiU3TKN3uWHd9gNERfCQ2aSm9w0LzbLqHU)

Here is the thing, there is 2 different project, one for specificly for API where you can access to data and second for website. with those POST request you are getting the data you want based on some properties, it's not creating or updating anything and it's okay to use that this way. second thing is https://war-track.com/ which is, website and using those endpoints it's completly different project written by Nextjs, it's only using API data. Again there is nothing wrong to use POST request in those cases, you will pass the filters and get relevant data that's it. You don't need to parse the website just use API endpoints in your app as documentation says and it should work. API starts with this url https://war-track.com/api/

**Comment by boomshakazulu** [comment]
noted. but just fyi those screenshots were taken from your website where the test "gets" are returning your entire website under your current instructions with "no params" option because these gets are pointed at a webpage. So using it as your documentation states returns bad data. even if you added the /api/ for the no params it would still return the html and styling of your api page.

anyway, keep up the good work and thanks

**Comment by nikasepiskveradze** [comment]
<img width="1665" alt="image" src="https://github.com/nikasepiskveradze/war-track-api/assets/62851300/439d005b-62b8-4132-aed6-5ef6d32739fb">
The API is meant to get data about "equipments" and "systems" data, the deafult "/" route in swagger is not API endpoint it's just the route generated by Swagger can't do anything with that at this point because of Swagger, just forget that endpoint. 

Basically we have website where I show some charts on url: https://war-track.com/
And we have Swagger docs website url: https://war-track.com/api/
And other routes are just API endpoints for getting/filtering the data, those are things probably you will need for your app
